spring:
  datasource:
    url: jdbc:h2:mem:devdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      javax:
        persistence:
          validation:
            mode: none
  sql:
    init:
      mode: always
      platform: h2
      schema-locations: classpath:sql/schema-*.sql
      data-locations: classpath:sql/data-*.sql
      encoding: UTF-8
      separator: ;
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: '*'

validation:
  message:
    source: classpath:messages
    encoding: UTF-8
    format:
      delimiter: ','
      separator: ':'
      prefix: '['
      suffix: ']'
    uniqueness:
      username: "Username '{}' is already taken"
      email: "Email '{}' is already taken"

session:
  id:
    length: 11
    generator:
      type: NUMERICAL
  duration:
    min: 20m
    max: 90m
    expiration:
      checkTimeInterval: 1s

image:
  generator:
    random:
      size: 8
      minSquare: 5