spring:
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: none
    properties:
      javax:
        persistence:
          validation:
            mode: none
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: false
  main:
    banner-mode: off
logging:
  level:
    root: warn
management:
  endpoints:
    web:
      exposure:
        exclude: '*'