INSERT INTO user_infos (id, firstname, lastname, created_at)
VALUES (1, 'firstname', 'lastname', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (2, 'Robert', 'BROWN', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (3, 'John', 'WILSON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (4, 'Michael', 'THOMSON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (5, 'William', 'ROBERTSON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (6, 'David', 'CAMPBELL', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (7, 'Richard', 'STEWART', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (8, 'Joseph', 'ANDERSON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (9, 'Thomas', 'MACDONALD', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (10, 'Charles', 'SCOTT', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (11, 'Christopher', 'REID', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (12, 'Daniel', 'MURRAY', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (13, 'Matthew', 'TAYLOR', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (14, 'Anthony', 'CLARK', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (15, 'Mark', 'MITCHELL', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (16, 'Donald', 'ROSS', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (17, 'Steven', 'WALKER', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (18, 'Paul', 'PATERSON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (19, 'Andrew', 'YOUNG', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (20, 'Joshua', 'WATSON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (21, 'Kenneth', 'MORRISON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (22, 'Kevin', 'MILLER', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (23, 'Brian', 'FRASER', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (24, 'George', 'DAVIDSON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (25, 'Edward', 'GRAY', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (26, 'Ronald', 'MCDONALD', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (27, 'Timothy', 'HENDERSON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (28, 'Jason', 'JOHNSTON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (29, 'Jeffrey', 'HAMILTON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (30, 'Ryan', 'GRAHAM', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (31, 'Jacob', 'KERR', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (32, 'Gary', 'SIMPSON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (33, 'Nicholas', 'MARTIN', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (34, 'Eric', 'FERGUSON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (35, 'Jonathan', 'CAMERON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (36, 'Stephen', 'DUNCAN', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (37, 'Larry', 'HUNTER', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (38, 'Justin', 'KELLY', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (39, 'Scott', 'BELL', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (40, 'Brandon', 'GRANT', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (41, 'Benjamin', 'MACKENZIE', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (42, 'Samuel', 'MACKAY', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (43, 'Gregory', 'ALLAN', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (44, 'Frank', 'BLACK', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (45, 'Alexander', 'MACLEOD', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (46, 'Raymond', 'MCLEAN', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (47, 'Patrick', 'RUSSELL', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (48, 'Jack', 'GIBSON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (49, 'Dennis', 'WALLACE', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (50, 'Jerry', 'GORDON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (51, 'Tyler', 'MARSHALL', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (52, 'Aaron', 'STEVENSON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (53, 'Jose', 'WOOD', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (54, 'Adam', 'SUTHERLAND', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (55, 'Henry', 'CRAIG', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (56, 'Nathan', 'WRIGHT', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (57, 'Douglas', 'MCKENZIE', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (58, 'Zachary', 'KENNEDY', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (59, 'Peter', 'JONES', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (60, 'Kyle', 'BURNS', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (61, 'Walter', 'WHITE', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (62, 'Ethan', 'MUIR', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (63, 'Jeremy', 'MURPHY', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (64, 'Harold', 'JOHNSTONE', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (65, 'Keith', 'HUGHES', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (66, 'Christian', 'WATT', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (67, 'Roger', 'MCMILLAN', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (68, 'Noah', 'MCINTOSH', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (69, 'Gerald', 'MILNE', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (70, 'Carl', 'MUNRO', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (71, 'Terry', 'RITCHIE', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (72, 'Sean', 'DICKSON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (73, 'Austin', 'BRUCE', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (74, 'Arthur', 'KING', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (75, 'Lawrence', 'CRAWFORD', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (76, 'Jesse', 'DOCHERTY', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (77, 'Dylan', 'MILLAR', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (78, 'Bryan', 'CUNNINGHAM', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (79, 'Joe', 'SINCLAIR', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (80, 'Jordan', 'WILLIAMSON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (81, 'Billy', 'HILL', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (82, 'Bruce', 'MCGREGOR', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (83, 'Albert', 'MCKAY', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (84, 'Willie', 'BOYLE', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (85, 'Gabriel', 'SHAW', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (86, 'Logan', 'FLEMING', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (87, 'Alan', 'MOORE', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (88, 'Juan', 'CHRISTIE', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (89, 'Wayne', 'DOUGLAS', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (90, 'Roy', 'DONALDSON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (91, 'Ralph', 'ALEXANDER', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (92, 'Randy', 'MACLEAN', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (93, 'Eugene', 'FORBES', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (94, 'Vincent', 'WILLIAMS', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (95, 'Russell', 'MCINTYRE', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (96, 'Elijah', 'FINDLAY', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (97, 'Louis', 'JAMIESON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (98, 'Bobby', 'AITKEN', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (99, 'Philip', 'REILLY', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000),
       (100, 'Johnny', 'THOMPSON', SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000);

insert into users (id, username, password, email, user_info_id)
values (1, 'user', '{noop}password', 'user@mail.com', 1),
       (2, 'rburborough1', '{noop}Z6gkSv2bPM', 'mgingle1@hostgator.com', 2),
       (3, 'dstollenbeck2', '{noop}TVBSJh', 'tmcinteer2@slashdot.org', 3),
       (4, 'srumsby3', '{noop}27PDXTBHO', 'tperillio3@t-online.de', 4),
       (5, 'rquinby4', '{noop}tym6yfopm2Ws', 'iludovici4@ftc.gov', 5),
       (6, 'evarcoe5', '{noop}FHb1IyTjFLMW', 'flecornu5@prnewswire.com', 6),
       (7, 'ebawdon6', '{noop}bbatQj', 'wfirman6@geocities.jp', 7),
       (8, 'blemerle7', '{noop}xYTE1T9jhY', 'vvanstone7@shutterfly.com', 8),
       (9, 'rpymm8', '{noop}M29M6sGnJnw', 'sdymond8@photobucket.com', 9),
       (10, 'ccopas9', '{noop}kukzOgFnjF', 'dlibbey9@ucoz.ru', 10),
       (11, 'mfeldmessera', '{noop}qP1eGk', 'awellstooda@bloomberg.com', 11),
       (12, 'mmakiverb', '{noop}xooenA8', 'dschaffelb@mail.ru', 12),
       (13, 'npetchc', '{noop}6w4xl7OhJiw', 'nkochsc@xrea.com', 13),
       (14, 'sbrockingd', '{noop}44haxkb', 'cdightond@cornell.edu', 14),
       (15, 'sshugge', '{noop}Oa2lMEd8j', 'tnashee@army.mil', 15),
       (16, 'dcoonanf', '{noop}Rc9mZUCql', 'imilkehamf@arizona.edu', 16),
       (17, 'tpierceyg', '{noop}CcEEocECTM', 'cfullmang@webeden.co.uk', 17),
       (18, 'twicksh', '{noop}TsXPWSweBQa', 'jfarquharsonh@shinystat.com', 18),
       (19, 'abudgeni', '{noop}ljUNBHSY4', 'mswalteridgei@dailymotion.com', 19),
       (20, 'cilewiczj', '{noop}gMYbnAwS', 'pcallenderj@engadget.com', 20),
       (21, 'lkeasleyk', '{noop}VaJJLZv0DEXp', 'ereviek@yolasite.com', 21),
       (22, 'cshirtliffl', '{noop}a05oIiu', 'gluttonl@yandex.ru', 22),
       (23, 'yrandellm', '{noop}eQ5aGCo96', 'eblackhallm@rambler.ru', 23),
       (24, 'deshelbyn', '{noop}r0LoL0', 'jferronetn@networksolutions.com', 24),
       (25, 'drobertazzio', '{noop}UPlSNL', 'tpearceyo@cornell.edu', 25),
       (26, 'mimpletonp', '{noop}3qBa4e1naSEj', 'slinkep@epa.gov', 26),
       (27, 'tkeyhoq', '{noop}wd9wRCDshi', 'rgaynorq@wsj.com', 27),
       (28, 'mburwellr', '{noop}cUslfs', 'ddumbellowr@usgs.gov', 28),
       (29, 'tderells', '{noop}Wa8wU7A75', 'rdarkes@homestead.com', 29),
       (30, 'rervint', '{noop}Wn4mDSHV719', 'dmcknisht@tinypic.com', 30),
       (31, 'lfuchsu', '{noop}OXrvXJ', 'ahaskayneu@so-net.ne.jp', 31),
       (32, 'jreinhartv', '{noop}0ozBp1qL5lw', 'apuddingv@youku.com', 32),
       (33, 'kbillyealdw', '{noop}OYDeaCylO', 'lcawtherayw@theguardian.com', 33),
       (34, 'maldwichx', '{noop}8afXQTq', 'jmarlorx@ameblo.jp', 34),
       (35, 'hdybally', '{noop}KKMlXaw3', 'hwyberny@shinystat.com', 35),
       (36, 'vchatz', '{noop}7csiYJ', 'bstaynesz@utexas.edu', 36),
       (37, 'abuglar10', '{noop}Tmu6Q7C', 'emayo10@ibm.com', 37),
       (38, 'breddle11', '{noop}wjcxnv0N', 'bjoslin11@icio.us', 38),
       (39, 'edietsche12', '{noop}YW5mIFvS8', 'cbellamy12@amazonaws.com', 39),
       (40, 'dsherwood13', '{noop}IzxkcQ', 'ttisun13@elegantthemes.com', 40),
       (41, 'dbeckworth14', '{noop}fSR9lbCNSr9', 'gblindmann14@nasa.gov', 41),
       (42, 'mmurray15', '{noop}pO3Cbdbo', 'pmacklam15@dion.ne.jp', 42),
       (43, 'lbillborough16', '{noop}GHer6KR6j', 'ngiddy16@hostgator.com', 43),
       (44, 'btowson17', '{noop}q0Wzdkl88v', 'abryer17@engadget.com', 44),
       (45, 'rhelwig18', '{noop}o9tAiv', 'lhughf18@hatena.ne.jp', 45),
       (46, 'asearch19', '{noop}KfZixKChYh', 'zcotesford19@disqus.com', 46),
       (47, 'mwhines1a', '{noop}mhNpVC757GQ', 'esteers1a@upenn.edu', 47),
       (48, 'gattwood1b', '{noop}hc6qiTR0lAIY', 'mausello1b@mac.com', 48),
       (49, 'dturban1c', '{noop}X7oZqt9FEcG', 'pferonet1c@ow.ly', 49),
       (50, 'bgirth1d', '{noop}AfBuck', 'ijordan1d@cornell.edu', 50),
       (51, 'scuttelar1e', '{noop}GqWt3DFD', 'lmathias1e@youtu.be', 51),
       (52, 'ngrover1f', '{noop}1cxRPUX', 'emacci1f@cocolog-nifty.com', 52),
       (53, 'jcogin1g', '{noop}ps9qOH', 'parrandale1g@wired.com', 53),
       (54, 'ktointon1h', '{noop}ogC6Bg0t', 'rbeamiss1h@dyndns.org', 54),
       (55, 'hcoughan1i', '{noop}bOPSbf2pD', 'bmarjot1i@boston.com', 55),
       (56, 'emumbey1j', '{noop}1AL8vvdYMZj', 'kdonan1j@hatena.ne.jp', 56),
       (57, 'fstadding1k', '{noop}0u28x626', 'ncristofano1k@constantcontact.com', 57),
       (58, 'halexandre1l', '{noop}Ccu4OYsaFdSU', 'equeree1l@live.com', 58),
       (59, 'eedlyne1m', '{noop}GhdzO6U', 'mguilloneau1m@zdnet.com', 59),
       (60, 'vspurdle1n', '{noop}2rq18C', 'lgilhespy1n@technorati.com', 60),
       (61, 'dheinel1o', '{noop}pziGGC', 'athomton1o@youku.com', 61),
       (62, 'gexell1p', '{noop}WS09nQDtIP', 'lbompas1p@diigo.com', 62),
       (63, 'dbeaumont1q', '{noop}1XYUcP', 'abengefield1q@wired.com', 63),
       (64, 'spowe1r', '{noop}kKE10V', 'evinall1r@wordpress.org', 64),
       (65, 'pkiebes1s', '{noop}IpiCCp6KH', 'bguerrero1s@xing.com', 65),
       (66, 'tskirling1t', '{noop}w7kBMid89', 'bbrammall1t@wufoo.com', 66),
       (67, 'asteet1u', '{noop}dvQL47', 'pellwood1u@disqus.com', 67),
       (68, 'gbennis1v', '{noop}VLw9QZT', 'ccarradice1v@howstuffworks.com', 68),
       (69, 'ajoll1w', '{noop}ZEKyfe2XP', 'gkeaves1w@mayoclinic.com', 69),
       (70, 'wsmissen1x', '{noop}RrbcWdX8', 'acarlisso1x@oracle.com', 70),
       (71, 'mjaskiewicz1y', '{noop}xkSR3JYaHhr', 'atorbett1y@prweb.com', 71),
       (72, 'jsivess1z', '{noop}Jxmyy3k', 'mbroughton1z@ocn.ne.jp', 72),
       (73, 'ascreen20', '{noop}pqoIwi', 'hallwright20@yahoo.com', 73),
       (74, 'hscoggans21', '{noop}uMp56Q', 'amorot21@bluehost.com', 74),
       (75, 'dfinch22', '{noop}aOX8Im2v', 'krenackowna22@pagesperso-orange.fr', 75),
       (76, 'jmenere23', '{noop}csGy3YSL59n', 'kkewish23@rakuten.co.jp', 76),
       (77, 'jnutley24', '{noop}T5bf5V532EjY', 'lbentley24@list-manage.com', 77),
       (78, 'emonkhouse25', '{noop}w2kKBiiEC', 'maguirrezabala25@phoca.cz', 78),
       (79, 'acastlake26', '{noop}LPR5PTmCN', 'bbretland26@hugedomains.com', 79),
       (80, 'bredmond27', '{noop}ncMYCkKu', 'hcadden27@google.pl', 80),
       (81, 'wspivie28', '{noop}CPLtBG8xAko', 'gowen28@etsy.com', 81),
       (82, 'wjellman29', '{noop}AHIYAOMh8J', 'dweippert29@fastcompany.com', 82),
       (83, 'khamfleet2a', '{noop}7yAdNzxa4nE', 'sbamber2a@purevolume.com', 83),
       (84, 'clongmore2b', '{noop}6tEMhM', 'npaolinelli2b@bravesites.com', 84),
       (85, 'dmcneely2c', '{noop}AnCObo8ckFEZ', 'zkinnen2c@smh.com.au', 85),
       (86, 'gdoodson2d', '{noop}xgXbGLaT', 'aorys2d@squarespace.com', 86),
       (87, 'agorgen2e', '{noop}dmMlUCLnsNY', 'ncanape2e@jugem.jp', 87),
       (88, 'nzimmermeister2f', '{noop}5Th9BWqu8Pw', 'jmassy2f@bloomberg.com', 88),
       (89, 'rmursell2g', '{noop}xT2JKM95OcdA', 'pmandre2g@thetimes.co.uk', 89),
       (90, 'mriccardini2h', '{noop}n2q8ox1', 'kgoves2h@trellian.com', 90),
       (91, 'nyankeev2i', '{noop}dmx2x4HS98B', 'proden2i@so-net.ne.jp', 91),
       (92, 'smcdarmid2j', '{noop}XlPja3', 'dpatrickson2j@guardian.co.uk', 92),
       (93, 'ahaggarth2k', '{noop}PB1c12g0J', 'cmilner2k@simplemachines.org', 93),
       (94, 'earnaudet2l', '{noop}pxFnrMXTelE', 'dmarlen2l@cdbaby.com', 94),
       (95, 'mmcdonough2m', '{noop}WmGeFQBangz', 'eallenby2m@who.int', 95),
       (96, 'cproffitt2n', '{noop}l961n2kHtsBC', 'cdenecamp2n@gizmodo.com', 96),
       (97, 'mgodbehere2o', '{noop}ktf1IWlCy', 'escottesmoor2o@google.ru', 97),
       (98, 'mburrells2p', '{noop}mid3Wb', 'bcarmen2p@cmu.edu', 98),
       (99, 'vgoodfield2q', '{noop}qo5oyBhg5', 'ewyss2q@ihg.com', 99),
       (100, 'jmapam2r', '{noop}GczdlPd0d1el', 'shardbattle2r@nih.gov', 100);

INSERT INTO sessions (id, name, user_id, created_at)
VALUES ('00000000000', 'test-session', 1, SELECT EXTRACT(EPOCH from CURRENT_TIMESTAMP()) * 1000)
